# Setup
title:               Quantus
tagline:             'A website by Jared Richard'
description:         'Just a Physicist who wants to know why.'
url:                 http://Jared-Richard.github.io
baseurl:             /Jared-Richard.github.io
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jared Richard
  url:               
  email:             jaredk.richard@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
